pipeline:
  test:
    image: golang:1.8.3-alpine
    commands:
      - go test ./...
  build:
    image: docker:dind
    commands:
      - docker build . -t bichon:${DRONE_COMMIT}
      - docker push quay.io/jibek_charette/bichon:${DRONE_COMMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

